spring:
  jpa:
    open-in-view: false
  data:
    mongodb:
      auto-index-creation: false

# local env
---
spring:
  profiles: local
  data:
    mongodb:
      host: localhost  #local에서는 'localhost', docker server에서는 'mongodb'로 설정
      port: 27017
      database: SCG
      authentication-database: admin
      username: 'username'
      password: 'password'

# dev env
---
spring:
  profiles: dev
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: SCG
      authentication-database: admin
      username: 'username'
      password: 'password'

# prod env
---
spring:
  profiles: prod
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: SCG
      authentication-database: admin
      username: 'username'
      password: 'password'