spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            scope: profile
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-name: Kakao
            client-authentication-method: POST
          naver:
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-name: Naver
            client-authentication-method: POST
          google:
            scope: profile,email
            client-name: Google
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

---
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "client id"
            client-secret: "client secret"
          google:
            client-id: "client id"
            client-secret: "client secret"
          naver:
            client-id: "client id"
            client-secret: "client secret"
# local env
---
spring:
  profiles: local
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "client id"
            client-secret: "client secret"
          google:
            client-id: "client id"
            client-secret: "client secret"
          naver:
            client-id: "client id"
            client-secret: "client secret"

# dev env
---
spring:
  profiles: dev
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "client id"
            client-secret: "client secret"
          google:
            client-id: "client id"
            client-secret: "client secret"
          naver:
            client-id: "client id"
            client-secret: "client secret"

# prod env
---
spring:
  profiles: prod
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "client id"
            client-secret: "client secret"
          google:
            client-id: "client id"
            client-secret: "client secret"
          naver:
            client-id: "client id"
            client-secret: "client secret"